# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ar_pg_array"
  s.version = "0.11.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sokolov Yura aka funny_falcon"]
  s.date = "2012-06-03"
  s.description = "ar_pg_array includes support of PostgreSQL's int[], float[], text[], timestamptz[] etc. into ActiveRecord. You could define migrations for array columns, query on array columns."
  s.email = "funny.falcon@gmail.com"
  s.extra_rdoc_files = [ "README.md" ]
  s.files = (Dir['lib/**/*']+Dir['spec/**/*']+%w{Gemfile init.rb MIT_LICENSE README Rakefile ar_pg_array.gemspec}).find_all{|f| File.file?(f)}
  s.homepage = "http://github.com/funny-falcon/activerecord-postgresql-arrays"
  s.require_paths = ["lib"]
  s.rubyforge_project = "ar-pg-array"
  s.summary = "Use power of PostgreSQL Arrays in ActiveRecord"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, ["< 4.0", ">= 3.0.6"])
    else
      s.add_dependency(%q<activerecord>, ["< 4.0", ">= 3.0.6"])
    end
  else
    s.add_dependency(%q<activerecord>, ["< 4.0", ">= 3.0.6"])
  end
end

